AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  blog-severless

  Sample SAM Template for blog-severless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BlogAdminApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: admin-api/
      Handler: admin.lambda_handler
      Runtime: python3.8
      Events:
        ArticleAdminGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /admin/article/{article-id}
            Method: get
        ArticleAdminPost:
          Type: Api
          Properties:
            Path: /admin/article
            Method: post
        ArticleAdminPut:
          Type: Api
          Properties:
            Path: /admin/article
            Method: put
        ArticleAdminDelete:
          Type: Api
          Properties:
            Path: /admin/article/{article-id}
            Method: delete
        ArticleAdminGetAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /admin/article/all
            Method: get
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref ArticleTable

  BlogReaderApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reader-api/
      Handler: reader.lambda_handler
      Runtime: python3.8
      Events:
        ArticleReaderGet:
          Type: Api
          Properties:
            Path: /reader/article/{article-id}
            Method: get
        ArticleReaderGetAll:
          Type: Api
          Properties:
            Path: /reader/article/all
            Method: get
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref ArticleTable

  ArticleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: blog-article
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        DeploymentType: SAM
      SSESpecification:
        SSEEnabled: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BlogAdminApi:
    Description: "API Gateway endpoint URL for Prod stage for Blog API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/admin/"
  BlogAdminApiFunction:
    Description: "Blog Lambda Function ARN"
    Value: !GetAtt BlogAdminApiFunction.Arn
  BlogAdminApiFunctionIamRole:
    Description: "Implicit IAM Role created for Blog API function"
    Value: !GetAtt BlogAdminApiFunctionRole.Arn
  BlogReaderApiFunction:
    Description: "Blog Reader Lambda Function ARN"
    Value: !GetAtt BlogReaderApiFunction.Arn
  BlogReaderApiFunctionIamRole:
    Description: "Implicit IAM Role created for Blog Reader API function"
    Value: !GetAtt BlogReaderApiFunctionRole.Arn
